### ISSUE TITLE
1.4 support

### ISSUE THREAD

**Issue by vanities** [beardedio/terraria#1]
Hey, just wanted to ask if you were going to throw 1.4 support in tonight/tomorrow, Thanks for your repo btw!

**Comment by vanities** [comment]
just fyi i think https://github.com/Penguax/terraria forked and did it

**Comment by Penguax** [comment]
> just fyi i think https://github.com/Penguax/terraria forked and did it

Hey, i forked it but im trying to push a docker image, its my first time doing that so im stuck, i emailed beardedio but i got no reply, im working on this, but for now you can host it on windows, once i get the docker running move the word over

**Comment by hskrtich** [comment]
I have update the repo with the new version. Let me know if you have any problems.

@Penguax What email did you use?

**Comment by JustinGrote** [comment]
I'm trying to start it in docker compose and got this:


```
jgrote@tinycloud:~/docker$ dc up terraria
Recreating terraria ... done
Attaching to terraria
terraria     | ﻿﻿﻿﻿Server crash: 5/17/2020 2:18:36 AM
terraria     | System.NullReferenceException: Object reference not set to an instance of an object
terraria     |   at Terraria.Main.DedServ () [0x009d3] in <13b27967e15e4b599e2813a00bd8f379>:0 
terraria     |   at Terraria.Program.LaunchGame (System.String[] args, System.Boolean monoArgs) [0x00092] in <13b27967e15e4b599e2813a00bd8f379>:0 
terraria     | 
terraria     | Please send crashlog.txt to support@terraria.org
```

my compose:
```

  terraria:
    container_name: terraria
    image: beardedio/terraria:vanilla-latest
    volumes:
      - ./terraria:/config
    ports:
      - "0.0.0.0:7777:7777"
    environment:
      - world=Quiet_Armpit.wld
```
