### ISSUE TITLE
Doc improve: docker-compose example

### ISSUE THREAD

**Issue by hxzhao527** [beardedio/terraria#16]
The `docker-compose` example  can't exec  [server command](https://terraria.gamepedia.com/Server#List_of_console_commands) after server startup.

According to the [docker-doc](https://docs.docker.com/engine/reference/run/#foreground), we need add `stdin_open: true`, 
```yaml
version: '3'
services:
  terraria:
    image: beardedio/terraria:vanilla-1.4.0.4
    ports:
      - '7777:7777'
    environment:
      - world=The_Common_Tropic.wld
    volumes:
      - ./config:/config
    tty: true
    stdin_open: true
```
Then, we can use `docker attach` to exec server-command.
