### ISSUE TITLE
NullReference error when updating from Tshock-pre 13 to pre 15 container

### ISSUE THREAD

**Issue by DoNotResuscitate** [beardedio/terraria#27]
Logs: 
```
Starting container, CMD: mono --server --gc=sgen -O=all TerrariaServer.exe -configpath /config -worldpath /config -worldselectpath /config -logpath /config -world /config/The_Island_of_Silver.wld
Error Logging Enabled.
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.0.5 (230), OTAPI 1.4.0.5)
[TShock] Info Config path has been set to /config
[TShock] Info World path has been set to /config
[TShock] Info Log path has been set to /config
TShock 4.4.0.0 (Go to sleep Patrikkk, Icy, Chris, Death, Axeel, Zaicon, hakusaro, Zack, and Yoraiz0r <3) now running.
AutoSave Enabled
Backups Enabled
Welcome to TShock for Terraria!
TShock comes with no warranty & is free softwar^[[20;1R^[[20;1R^[[20;1Re.
You can modify & distribute it under the terms of the GNU GPLv3.
[Server API] Info Plugin TShock v4.4.0.0 (by The TShock Team) initiated.
Server crash: 11/18/2020 2:55:46 AM
System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.DedServ () [0x00a07] in <b823b82d9daf48e59d7ebe55aa874ffb>:0
  at Terraria.Program.LaunchGame (System.String[] args, System.Boolean monoArgs) [0x000ac] in <b823b82d9daf48e59d7ebe55aa874ffb>:0
```
Docker-compose:
```
terraria2:
        image: beardedio/terraria:tshock-latest
        container_name: terraria2
        ports:
            - 7778:7778
        environment:
            - world=The_Island_of_Silver.wld
        volumes:
            - /home/alex/docker/terraria/config2:/config
        tty: true
        stdin_open: true
        restart: unless-stopped
```

If I revert back to older image it works just fine
