### ISSUE TITLE
vanilla-latest still points to 1.3

### ISSUE THREAD

**Issue by JustinGrote** [beardedio/terraria#3]
I was so confused :)

**Comment by juanrodgil** [comment]
Yes, and give an error with a 1.4 map!
 i'm using right now the specific version tag, like vanilla-1.4.0.2 until this is fixed

**Comment by JackOneil** [comment]
@juanrodgil Does it work for you ? Im getting some errors with my docker-compose after 
```
Settling liquids 49%
Settling liquids 50%
Terraria Server v1.4.0.2
Listening on port 7777
Type 'help' for a list of commands.
: ================
05/17/2020 09:00:15: Unhandled Exception
Thread: 6 [Server Input Thread]
Culture: 
Exception: System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.startDedInputCallBack () [0x00017] in <4ca1e6c0de0846809f149ffc19998e7b>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <1170fb08300b4d0db71c1d1db8555768>:0 
================
﻿﻿[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.startDedInputCallBack () [0x00017] in <4ca1e6c0de0846809f149ffc19998e7b>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <1170fb08300b4d0db71c1d1db8555768>:0 
```
my docker-compose.yml:
```
version: '2'

services:

  terraria:
    image: beardedio/terraria:vanilla-1.4.0.2
    environment:
      world: Bayou_of_Confusion.wld
    volumes:
     - /opt/terraria/config:/config
    ports:
      - 7777:7777
```

EDIT: i have tried to run only with `docker run` and that works fine. Will try to debug the compose more.

**Comment by juanrodgil** [comment]
This works for me:


```
version: '3.5'

services:

  terraria:
    container_name: terraria
    restart: unless-stopped
    image: beardedio/terraria:vanilla-1.4.0.2
    environment:
      world: myworld.wld
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    volumes:
      - ${CONFIG_PATH}/terraria:/config
    networks:
      - default

networks:
  default:
    driver: bridge
```


I dont know if the stdin and tty are really necessary, but i see them on other docker compose examples for terraria
