### ISSUE TITLE
Clean shutdown

### ISSUE THREAD

**Issue by bdr99** [beardedio/terraria#4]
When I stop this container, does it perform a clean shutdown of the server? In other words, does it command the Terraria server to save the world file before killing the process? Or is it possible that world data could be lost upon stopping the container if the world file was not saved recently?

If not, then can the container be modified to include this feature so that world data will not be lost?

docker-compose config:
```
version: '3.5'
services:
  terraria:
    image: beardedio/terraria
    container_name: terraria
    environment:
      - world=world.wld
    ports:
      - 7777:7777
    volumes:
      - ./config:/config
    restart: unless-stopped
    stdin_open: true
    tty: true
```
