### ISSUE TITLE
Docker compose world file does not exist

### ISSUE THREAD

**Issue by ashmoreinc** [beardedio/terraria#40]
For the latest version (1.4.3.6), The error "World file does not exist! Quitting..." error is returned even when supplying the world file and the config file volume.  When using `sudo docker compose up`

# Error
![image](https://user-images.githubusercontent.com/12419736/175933854-6aa9d079-b1a3-4bb6-8691-9b790ecbbd34.png)

# Docker compose file
![image](https://user-images.githubusercontent.com/12419736/175933888-99162262-f787-43e1-9dba-5661987610c2.png)

```
version: '3'
services:
    terraria:
        image: beardedio/terraria:vanilla-latest
        ports:
            - 7777:7777
        restart: unless-stopped
        environment:
            - world=World.wld
        volumes:
            - $HOME/DockerFiles/terraria/config:/config
        tty: true
        stdin_open: true
```
# Path showing file exists
![image](https://user-images.githubusercontent.com/12419736/175933939-7b0610dc-d0bd-4d0a-b108-082b705ea377.png)
