### ISSUE TITLE
It is possible to save world locally?

### ISSUE THREAD

**Issue by bearaujus** [beardedio/terraria#58]
So, in docker compose I want to use commands like:
```
'volumes': ['/folder/my-world:somewhere in the container']
```
This purposes to save the world locally in my storage.

And finally if I run 'docker stop x', inside the container will run command 'exit' first right?

*ps. I never tried this container yet:D

**Comment by PengXuanyao** [comment]
Hi, the official doc shows this docker compose file:

```
version: '3'

services:
  terraria:
    image: ghcr.io/beardedio/terraria:latest
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      - world=<world_file_name>
    volumes:
      - $HOME/terraria/config:/config
    tty: true
    stdin_open: true
```

and the script above already can get the world saved locally by:

```
    volumes:
      - $HOME/terraria/config:/config
```

you can just put your world in `$HOME/terraria/config` , and set the `<world_file_name>` as your world file name.(eg. `new_world.wld`, btw don't forget `.wld`)

and if you don't have any world, and you create it in docker, the world will save in `$HOME/terraria/config`.
