### ISSUE TITLE
TShock configuration

### ISSUE THREAD

**Issue by legacik** [beardedio/terraria#59]
Hi,

is it possible to use local TShock config.json, also server whiltelist etc?

I'm running image via docker-compose:

`version: '3'

services:
  terraria:
    image: ghcr.io/beardedio/terraria:tshock-latest
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      - world=dontdigup.wld
    volumes:
      - /srv/terraria/dontdigup-tshock/config:/config
      - /srv/terraria/dontdigup-tshock/ServerPlugins:/tshock/ServerPlugins
    tty: true
    stdin_open: true`

Thanks.

**Comment by syorito-hatsuki** [comment]
> Hi,
> 
> is it possible to use local TShock config.json, also server whiltelist etc?
> 
> I'm running image via docker-compose:
> 
> `version: '3'
> 
> services: terraria: image: ghcr.io/beardedio/terraria:tshock-latest ports: - '7777:7777' restart: unless-stopped environment: - world=dontdigup.wld volumes: - /srv/terraria/dontdigup-tshock/config:/config - /srv/terraria/dontdigup-tshock/ServerPlugins:/tshock/ServerPlugins tty: true stdin_open: true`
> 
> Thanks.

Codeblock fix (not issue fix)
```yaml
version: '3'

services:
  terraria:
    image: ghcr.io/beardedio/terraria:tshock-latest
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      - world=dontdigup.wld
    volumes:
      - /srv/terraria/dontdigup-tshock/config:/config
      - /srv/terraria/dontdigup-tshock/ServerPlugins:/tshock/ServerPlugins
    tty: true
    stdin_open: true
```
