### ISSUE TITLE
System.NullReferenceException when loading a world

### ISSUE THREAD

**Issue by NoeelMoeskops** [beardedio/terraria#7]
1.4.0.2 server returns a "System.NullReferenceException" exception when loading a world.

[server log](https://pastebin.com/0FV9w8Ty)

**Comment by Hoi15A** [comment]
I got that issue as well. One thing to note is that I couldn't even get vanilla terraria to run. I think it may just be an issue with terraria itself.

**Comment by TechInterMezzo** [comment]
Same here and I couldn't find that error on Google or the official Terraria forum. I have no idea what's causing this.

**Comment by ss89** [comment]
Have you guys started the image interactive and with a tty assigned? "docker run -it ..."?

**Comment by Noutbuk** [comment]
Same issue on my side, but only if I try to run the container as part of a docker-compose.yml file like the following one:
```
version: '3'
services:
  terraria:
    image: beardedio/terraria:vanilla-1.4.0.2
    ports:
      - '7777:7777'
    restart: always
    environment:
      - world=worldfile.wld
    volumes:
      - ./config:/config
```

If I start the server using `docker run`, it runs just fine.
```
sudo docker run -it -p 7777:7777 -v /path/to/config:/config -e world=worldfile.wld --name=terraria beardedio/terraria:vanilla-1.4.0.2
```

**Comment by TechInterMezzo** [comment]
You are right. The problem is not occurring with docker run, only with docker-compose. So what's the difference?

**Comment by Noutbuk** [comment]
I managed to solve/circumvent the problem now with the following `docker-compose.yml`. Notice the additional line at the bottom. As far as I understand, the Terraria server requires an open shell, which is present when running `docker run -it`. The additional line provide this shell to the docker container in docker-compose.

```
version: '3'

services:
  terraria:
    image: beardedio/terraria:vanilla-1.4.0.2
    ports:
      - '7777:7777'
    restart: always
    environment:
      - world=worldfile.wld
    volumes:
      - ./config:/config
    tty: true
```

I hope, this also works for the others.
